export const CORRECT = "CORRECT"
export const INCORRECT = "INCORRECT"
export const VERSE_VIEW = "VERSE_VIEW"
export const ADD_VERSE = "ADD_VERSE"
export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "HIDE_ALERT"